### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by theyanglu** [hcbille/install-tizenbrew-tizen#2]
Just ran this in portainer with the following stack command:
```
services:
    install-tizen-brew:
        image: hcbille/install-tizenbrew-tizen
        command: 10.0.1.85
```
and it was unable to deploy onto the TV.  I've run similar code for Jellyfin with no issue.  Here is the log from the container.  Looks like the TV was found, but there was no package found in the image.

```
Thanks to https://github.com/reisxd/ for providing the pre-packaged TizenBrew builds!

	These builds can be found at https://github.com/reisxd/TizenBrew

Attempting to connect to Samsung TV at IP address 10.0.1.85

* Server is not running. Start it now on port 26099 *

* Server has started successfully *

connecting to 10.0.1.85:26101 ...

connected to 10.0.1.85:26101

Attempting to get the TV name...

Found TV name: QN65Q6FNA

There is no package with named TizenBrewStandalone.wgt.

[Fail] Fail install. There is the problem about package.

Total time: 00:00:00.746
```
